[package]
name = "rust-jni"
version = "0.1.0"
edition = "2021"

[dependencies]
jni = "0.21.1"
tokio = { version = "1", features = ["full"] }
warp = "0.3"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"

[lib]
crate-type = ["cdylib"]
