# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: node:12
    steps:
    - uses: actions/checkout@v2
    - run: npm i -g github-markdown
    - run: rm -rf .git
    - run: bash ./bootstrap.sh
    - run: git init
    - run: git config user.name "frank"
    - run: git config user.email "sunwu51@126.com"
    - run: git add .
    - run: git commit -m "update note"
    - env:
        TOKEN: ${{ secrets.TOKEN }}
      run: git push --force https://$TOKEN@github.com/xiaogenban1993/xiaogenban1993.github.io.git master
